apiVersion: v1
kind: Pod
metadata:
  name: not-privileged
spec:
  containers:
  - image: alpine
    name: alpine
    stdin: true
    tty: true
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
  restartPolicy: Never
