apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-privileged-psp
  namespace: kube-system
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - privileged
