apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dangerous-deploy
  name: dangerous-deploy
  namespace: psp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dangerous-deploy
  template:
    metadata:
      labels:
        app: dangerous-deploy
    spec:
      containers:
      - image: alpine
        name: alpine
        stdin: true
        tty: true
        securityContext:
          privileged: true
      hostPID: true
      hostNetwork: true
