apiVersion: v1
kind: Pod
metadata:
  name: sudo-test
spec:
  containers:
  - image: alpine
    name: sudo-test
    stdin: true
    tty: true
    securityContext:
      privileged: true
  hostNetwork: true
  hostPID: true
  restartPolicy: Never
